## HOW IT WORKS: the game on five pages, from the pause menu. What a day is, how you get about,
## where money comes from, the police, and who Leo's turning into.
class_name HowItWorks
extends RefCounted

const PAGES := [
	["YOUR DAYS", "LEO WORKS THE COUNTER AT COVINGTON AUTO. EVERY DAY HAS TWO HALVES.|MORNINGS: THE COUNTER. CARS COME IN FOR INSPECTION. CHECK EACH ONE AGAINST ITS PAPERS AND THE DAY'S RULES, THEN PASS IT OR FAIL IT. THE RULES PILE UP AS THE WEEKS GO BY, AND THE SHIFT PAYS A WAGE.|EVENINGS: THE ROAD. IF THE STORY HAS A DRIVE FOR TONIGHT, THE GPS ALREADY KNOWS WHERE. IF NOT, THE TOWN'S YOURS.|THE STORY MOVES ON IN THE CUTSCENES BETWEEN THEM."],
	["GETTING AROUND", "THE LINE AT THE TOP OF THE SCREEN ALWAYS SAYS WHAT YOU'RE DOING NOW.|{map}: THE MAP. PICK A PLACE AND THE GPS DRAWS THE WAY THERE, RIGHT INTO ITS LOT. MISS A TURN AND IT WORKS OUT A NEW WAY.|{reset}: STUCK? TOBY TOWS YOU HOME (NOT IN THE MIDDLE OF A POLICE CHASE).|{help}: THE CONTROLS.  T: THE CAMERA ANGLE."],
	["MONEY", "IN: THE COUNTER'S WAGE, AND THE PHONE ({jobs}): GIGS (PIZZA, TOW CALLS, RIDES, STREET RACES).|OUT: GAS, TICKETS, REPAIRS, PARTS AND CARS.|GUS'S GARAGE AT COVINGTON AUTO FIXES AND BUILDS YOUR CAR. MARKETTHING, ON THE PHONE, BUYS AND SELLS CARS. NORTHSIDE SALVAGE HAS USED PARTS, AND THE IMPOUND LOT AUCTIONS WHAT NOBODY CAME BACK FOR ON SATURDAYS."],
	["THE POLICE AND THE ROAD", "SPEED, RACE OR RUN A RED WHERE A PATROL CAR CAN SEE YOU AND THEY LIGHT YOU UP. PULL OVER AND IT'S A TICKET. RUN AND THE HEAT CLIMBS UNTIL YOU LOSE THEM OR THEY IMPOUND THE CAR.|BUILDINGS BLOCK WHAT YOU CAN SEE, AND WHAT THEY CAN.|PUT YOUR CAR INTO SOMEBODY'S AND STAY FOR THE POLICE. DRIVE OFF AND IT'S A HIT AND RUN.|THE CAR KEEPS ITS DAMAGE, ITS WEAR AND ITS TEMPERATURE. WATCH THE GAUGES AND THE SCAN TOOL."],
	["WHO LEO IS", "WHAT LEO SAYS IN THE CUTSCENES, AND HOW HE DRIVES IN THE STORY, MAKE HIM COOL, CALM AND COLLECTED, OR RECKLESS, OR SOMEWHERE IN BETWEEN.|PEOPLE TALK TO HIM THE WAY HE'S EARNED. THE POLICE GIVE A CALM DRIVER A LITTLE SLACK AND A RECKLESS ONE NONE. AND IT DECIDES HOW THE STORY ENDS.|THE CHAPTER CARDS SAY WHERE HE STANDS."],
]

## A page's paragraphs, keys filled in for whatever you're holding, wrapped to `chars` of the old
## fixed-width font.
static func lines(page: int, chars: int) -> Array[String]:
	var out: Array[String] = []
	var paras: PackedStringArray = Hints.fmt(String(PAGES[page][1])).split("|")
	for k in paras.size():
		if k > 0: out.append("")
		out.append_array(Hud.wrap_lines(paras[k], chars))
	return out
