## The story, as data: who's in it, what they say, and the order things happen in.
##
## A scene is a set (a background drawn by code) and a list of lines:
##   [speaker, text]               a line of dialogue ("*" is narration, no portrait)
##   ["choice", [[label, flag], ...]]   Leo picks; the flag is remembered
##   ["set", name]                 go somewhere else mid-scene (a fade through black)
##   ["cast", [[who, x, facing, pose], ...]]   who's standing there now (after a "set")
##   ["cash", amount]              money changes hands
##   ["flag", name]                remember something
##   ["pose", who, pose]           someone in the scene changes pose (stand, crossed, pockets, cup, phone, bow, point, hips, wave)
## Any line (or a choice's option) can end with a condition, {"karma": "low"}, {"flag": "kid_home"},
## {"not_flag": "x"}: it only plays for a Leo it fits (see Karma.holds). People talk to a reckless
## Leo differently from a calm one, and the endings branch the same way (a step's "if").
## A scene's "cast" is who's standing in the set: [who, x (0..320), facing (1 right / -1 left), pose].
## Anyone who speaks but isn't in the cast is on Leo's phone (texts).
## Text can use {MANAGER} (the old manager's name), {CASH} and {DEBT}.
class_name StoryScript
extends RefCounted

## The cast. seed + female + age go straight into the CAGE BOSS portrait generator.
const CAST := {
	"LEO":       { "name": "LEO", "seed": 190019, "female": 0, "age": 19, "color": "d9a441" },
	"MIKEY":     { "name": "MIKEY", "seed": 420069, "female": 0, "age": 19, "color": "6fbf5a" },
	"GUS":       { "name": "GUS", "seed": 198101, "female": 0, "age": 70, "color": "c8c0a8" },
	"DOM":       { "name": "DOM TORTELLINI", "seed": 777001, "female": 0, "age": 46, "color": "e0402e" },
	"MIA":       { "name": "MIA TORTELLINI", "seed": 777002, "female": 1, "age": 38, "color": "e07a9a" },
	"SAL":       { "name": "SAL", "seed": 777013, "female": 0, "age": 33, "color": "a85a4a" },
	"ARIES":     { "name": "ARIES", "seed": 140014, "female": 1, "age": 14, "color": "7ab8e0" },
	"TOBY":      { "name": "TOBY CORMIER", "seed": 506506, "female": 0, "age": 31, "color": "ffa020" },
	"TREMBLAY":  { "name": "CONST. TREMBLAY", "seed": 911911, "female": 1, "age": 41, "color": "4a7ab8" },
	"DARRELL":   { "name": "DARRELL (SELLER)", "seed": 900900, "female": 0, "age": 58, "color": "8a8478" },
	"FRANK":     { "name": "FRANK COVINGTON", "seed": 190001, "female": 0, "age": 49, "color": "c8c0a8" },
	"FRANKIE":   { "name": "FRANKIE", "seed": 130624, "female": 0, "age": 13, "color": "e07a3a" },
	"FRANKIE19": { "name": "FRANKIE", "seed": 130624, "female": 0, "age": 19, "color": "e07a3a" },
	"HATCH":     { "name": "DALE HATCH", "seed": 551155, "female": 0, "age": 56, "color": "c8a050" },
}

const SCENES := {
	# ------------------------------------------------------------------ prologue
	"party": { "set": "party", "cast": [["LEO", 120, 1, "cup"], ["MIKEY", 186, -1, "cup"]], "lines": [
		["*", "A WAREHOUSE ON INDUSTRIAL DRIVE. SOMEBODY'S COUSIN'S BIRTHDAY. NOBODY KNOWS WHOSE."],
		["MIKEY", "Leo. LEO. Buddy. You've been staring at that speaker for ten minutes."],
		["LEO", "It's breathing, Mikey. The speaker's breathing."],
		["MIKEY", "That's the bass, man. Also the edible. Mostly the edible."],
		["LEO", "Ten months tomorrow. Since Dad."],
		["MIKEY", "...Yeah. I know, bud."],
		["LEO", "Everybody keeps saying he was drunk. Twenty years sober and he goes off the Coast Road with a forty in him? Sure."],
		["MIKEY", "You want to talk about it?"],
		["LEO", "I want another one of whatever this is."],
		["*", "TWO HOURS AND SEVERAL BAD DECISIONS LATER."],
		["MIKEY", "Where are you going? Your keys are in my hat. Why are your keys in my hat."],
		["LEO", "Taking Dad's Supreem home. It's two kilometres. It's fine."],
		["MIKEY", "Are you good to drive?"],
		["choice", [["\"I'm always good to drive.\"", "cocky"], ["\"...Yeah.\"", "quiet"], ["\"Mikey. Look at me. I'm a professional.\"", "joke"]]],
		["MIKEY", "Nobody who's always good to drive says that, bud. Nobody.", { "flag": "cocky" }],
		["MIKEY", "...Text me when you're home. Use words. Not just the eggplant."],
	]},
	"the_meet": { "set": "airstrip", "cast": [["MIA", 14, 1, "hips"], ["LEO", 216, -1, "stand"], ["DOM", 252, -1, "crossed"], ["SAL", 292, -1, "pockets"]], "lines": [
		["*", "AIRSTRIP 7. FRIDAY NIGHT. THE FAMILIA'S MEET."],
		["*", "TWENTY CARS IN A CIRCLE. HEADLIGHTS ON. TWO OF THEM ARE NOW NOSE TO NOSE. PERMANENTLY."],
		["MIA", "That's my car. That WAS my car. Dom. DOM. He parked in my car's FACE."],
		["SAL", "Kid came through the fence at like a hundred and forty. Nobody was chasing him. He was chasing himself."],
		["LEO", "I'm... okay. I'm okay. Is everybody okay? Whose turbo is that on the ground?"],
		["MIA", "MINE. That's my turbo. On the ground. Where turbos don't go."],
		["DOM", "Everybody. Quiet."],
		["*", "DOM TORTELLINI WALKS AROUND THE WRECK ONCE. SLOWLY. THEN HE BOWS HIS HEAD."],
		["pose", "DOM", "bow"],
		["pose", "SAL", "bow"],
		["DOM", "Lord. Thank you for this meet. For the cars. For the family. For the kid who didn't die tonight, even though he tried his best."],
		["DOM", "Amen."],
		["SAL", "Amen."],
		["pose", "DOM", "crossed"],
		["pose", "SAL", "pockets"],
		["MIA", "...Amen. I'm still going to kill him."],
		["DOM", "You're Frank Covington's kid."],
		["LEO", "You knew my dad?"],
		["DOM", "Everybody knew your dad. Your dad fixed my first car on credit. Never asked for the money. Never had to."],
		["pose", "DOM", "point"],
		["DOM", "You broke family's car. So now you work for family."],
		["pose", "DOM", "crossed"],
		["DOM", "Your father's garage? It's a nice garage. Be a shame if it was... legitimate."],
		["LEO", "It has an inspection licence. You can't just—"],
		["DOM", "I know. That's why it's a nice garage."],
		["MIA", "Forty-two hundred. For the car. Plus my turbo. Plus my feelings."],
		["DOM", "Mia. We're not monsters. Forty-two hundred. The feelings are free."],
		["choice", [["\"Okay. Okay. I'll pay it.\"", "meet_agree"], ["\"And if I say no?\"", "meet_defiant"]]],
		["DOM", "Good. Your father paid what he owed, too. Go home, Leo. Walk. Sal will bring the car.", { "flag": "meet_agree" }],
		["DOM", "Then you say no, and tomorrow you still owe us, and you're also the kid who said no. Go home, Leo. Walk. Sal will bring the car.", { "flag": "meet_defiant" }],
		["SAL", "The car's in four pieces, Dom."],
		["DOM", "Then bring all four. Family doesn't leave pieces behind."],
		["flag", "owes_familia"],
	]},
	"gus_morning": { "set": "office", "cast": [["GUS", 70, 1, "crossed"], ["LEO", 246, -1, "stand"]], "lines": [
		["*", "COVINGTON AUTO. 7:58 A.M. LEO HAS A HEADACHE SHAPED LIKE A SUPREEM."],
		["GUS", "You look like something I'd drain out of a transmission."],
		["LEO", "Morning, Gus."],
		["GUS", "Toby towed what's left of your father's car in at six. Says you went through a fence at Airstrip 7."],
		["GUS", "Says the Tortellinis were there. Says Dom said grace."],
		["LEO", "He's... a very spiritual man."],
		["GUS", "He's a very something man."],
		["GUS", "Toby says you looked Dom Tortellini in the eye and said \"and if I say no.\" Your father would've laughed. Then he'd have hit you.", { "flag": "meet_defiant" }],
		["GUS", "Toby says you told him you'd pay. Good. Polite keeps your teeth in.", { "flag": "meet_agree" }],
		["GUS", "Front counter's yours now. Your father left you the shop, and the shop comes with the counter, and the counter comes with the Ministry."],
		["GUS", "Every car that wants a sticker, you read every paper. VIN on the ownership against the VIN on the dash. I read it off the car myself. Every one."],
		["LEO", "Who ran the counter before Dad's... before?"],
		["GUS", "{MANAGER}. Ran it for years, then one day didn't. Left a drawer full of pens and a coffee mug that says WORLD'S OKAYEST BOSS."],
		["pose", "GUS", "point"],
		["GUS", "Don't touch the mug."],
	]},
	"clock_out_1": { "set": "lot_dusk", "cast": [["GUS", 128, 1, "crossed"], ["LEO", 184, -1, "pockets"]], "lines": [
		["*", "CLOCK OUT. 6:02 P.M."],
		["GUS", "Not bad. Not good. Not bad. Your father's first day he passed a car with no brakes, so you're ahead of him."],
		["LEO", "Dad passed a car with no brakes?"],
		["GUS", "Once. Never again. Checked his own every Sunday after that. Every single Sunday."],
		["pose", "LEO", "phone"],
		["*", "LEO'S PHONE BUZZES. TWICE."],
		["ARIES", "are u alive. toby said u drove into the mafia"],
		["LEO", "Not the mafia. A family. With a lot of cars."],
		["ARIES", "thats the mafia leo"],
		["ARIES", "also we have no milk. and no car. and i have practice at 7 tomorrow"],
		["*", "ANOTHER BUZZ. MIKEY."],
		["MIKEY", "found u a car on MarketThing. $900. 'RUNS GREAT.' guy says meet at the tim burtons on Mountain Rd. bring cash. i put in $500 from my college fund (the jar)"],
		["LEO", "Mikey, that jar is for college."],
		["MIKEY", "bro the jar is for emergencies. u are an emergency"],
		["TOBY", "Heard you need a ride to the Tim Burtons. Take the wrecker. Don't touch the boom. Don't touch the radio. Don't eat the Burton Bits on the dash, they're evidence."],
	]},
	"runs_great": { "set": "tims", "cast": [["LEO", 124, 1, "stand"], ["DARRELL", 172, -1, "hips"]], "lines": [
		["*", "TIM BURTONS, MOUNTAIN ROAD. A '91 NISSUN SILVIO UNDER THE ONLY LAMP THAT WORKS."],
		["DARRELL", "You Mikey's guy?"],
		["pose", "LEO", "pockets"],
		["LEO", "I'm Mikey's guy."],
		["DARRELL", "Runs great. Needs nothing. Selling it for my wife's husband."],
		["LEO", "...Isn't that you?"],
		["DARRELL", "Hence the price."],
		["pose", "LEO", "point"],
		["LEO", "Why's there a puddle under it?"],
		["pose", "LEO", "stand"],
		["DARRELL", "That's a rain puddle."],
		["LEO", "It hasn't rained in a week."],
		["DARRELL", "It's a very old rain puddle. Nine hundred. No lowballs, I know what I have."],
		["choice", [["Pop the hood first.", "checked_silvio"], ["\"Deal.\" (Hand over the cash.)", "blind_buy"]]],
		["DARRELL", "Oil's a little milky. That's normal. That's how they came from the factory. Like a latte."],
		["DARRELL", "That's eight-forty. I said nine."],
		["LEO", "It's everything I have. And everything Mikey's jar had."],
		["DARRELL", "...Fine. The other sixty was for the puddle anyway."],
		["cash", -340],
		["DARRELL", "Pleasure doing business. Don't call me. The number's my wife's husband's."],
		["flag", "owns_silvio"],
		["*", "IT STARTS ON THE THIRD TRY. IT SOUNDS LIKE A BLENDER FULL OF BOLTS. IT IS THE MOST BEAUTIFUL THING LEO HAS EVER OWNED."],
	]},
	"home_night": { "set": "apartment", "cast": [["LEO", 140, 1, "stand"], ["ARIES", 222, -1, "crossed"]], "lines": [
		["*", "THE APARTMENT OVER THE GARAGE. 11:40 P.M."],
		["ARIES", "Is that your new car? It sounds like it's crying."],
		["LEO", "It's singing."],
		["ARIES", "It's leaking on Gus's spot. He's going to kill you."],
		["ARIES", "...Leo. You smelled like a bar last night. Toby told me about the fence."],
		["LEO", "I'm fine."],
		["ARIES", "Dad used to say that. Right up until."],
		["ARIES", "Mikey says you told him you're always good to drive. Dad never said that. Not once.", { "flag": "cocky" }],
		["ARIES", "And Mikey says you made Darrell pop the hood first. That's what Dad would've done.", { "flag": "checked_silvio" }],
		["*", "SHE GOES TO BED. LEO SITS IN THE DARK FOR A WHILE."],
		["set", "bay"],
		["cast", []],
		["*", "DOWNSTAIRS, IN THE BAY, THE SILVIO TICKS AS IT COOLS DOWN."],
	]},
	# ------------------------------------------------------------------ chapter 1
	"clock_out_2": { "set": "lot_dusk_charjer", "cast": [["LEO", 128, 1, "stand"], ["MIA", 186, -1, "hips"]], "lines": [
		["*", "CLOCK OUT. A BLACK DODGY CHARJER IS IDLING ACROSS THE STREET. IT HAS BEEN IDLING ACROSS THE STREET FOR AN HOUR."],
		["MIA", "Leo. Walk with me."],
		["pose", "MIA", "crossed"],
		["MIA", "Dom wants you to start paying. Tonight there's a car at Airstrip 7. Black Charjer, the other one. Bring it here. Bay 3."],
		["LEO", "What's wrong with it?"],
		["MIA", "Nothing's wrong with it. Something's wrong with its paperwork. That's your department now."],
		["MIA", "Not a scratch on it, Leo. Every scratch comes off your forty-two hundred. In the wrong direction."],
		["LEO", "Mia, I'm sorry about your car."],
		["MIA", "...It was a good car. My dad built it. Don't make me cry in front of the Tim Burtons."],
	]},
	"bay_three": { "set": "bay", "cast": [["LEO", 100, 1, "pockets"], ["GUS", 160, -1, "stand"]], "lines": [
		["*", "BAY 3. THE CHARJER SITS UNDER A TARP. GUS IS NOT LOOKING AT IT VERY HARD."],
		["GUS", "Your father had a bay like this once. Before you were born. Before he went straight."],
		["LEO", "Dad never talked about before."],
		["GUS", "No. He didn't."],
		["GUS", "He checked his brakes every Sunday, Leo. Every Sunday for twenty years. You know what kind of man misses his brakes the one week it snows?"],
		["GUS", "Wrote it down, too. Little green book, in pencil. Nobody knew about that book but me and you kids. It wasn't in the car when Toby towed it."],
		["flag", "clue_green_book"],
		["LEO", "A drunk one. That's what the report says."],
		["pose", "GUS", "crossed"],
		["GUS", "Report says a lot of things. Reports get written by people."],
		["GUS", "And you, kid. Every cop in Port Rumble knows your plate already. You drive like that, you'll end up like that report says he did.", { "karma": "low" }],
		["GUS", "You've got his hands, kid. Careful hands. Don't waste them.", { "karma": "high" }],
		["*", "GUS GOES BACK TO WORK. HE DOESN'T SAY ANOTHER WORD ALL NIGHT."],
		["flag", "clue_brakes"],
	]},
	# ------------------------------------------------------------------ Frankie
	"the_kid": { "set": "bay", "cast": [["LEO", 56, 1, "stand"], ["FRANKIE", 106, -1, "pockets"], ["GUS", 172, -1, "crossed"]], "lines": [
		["*", "BAY 3. A WEEK LATER. ALL WEEK THERE'S BEEN A KID ON THE CURB OUT FRONT AT CLOSING, WATCHING THROUGH THE BAY WINDOW. TONIGHT THE KID IS INSIDE."],
		["FRANKIE", "Your back left's low. Like, really low. I could hear it when you pulled in."],
		["FRANKIE", "Everybody on my street knows your car. You're the guy who drove through the fence at the airstrip. That's so sick.", { "karma": "low" }],
		["FRANKIE", "My mom says you're the one at Covington's who actually reads the papers. She says that's rare.", { "karma": "high" }],
		["LEO", "Who let you in here?"],
		["FRANKIE", "Side door. The latch is broke. I fixed it, actually. Then I broke it again so nobody would know."],
		["GUS", "He's been on that curb every night since Monday. Like a cat. I figured if I fed him he'd go away."],
		["GUS", "I fed him. He did not go away."],
		["LEO", "It's ten o'clock on a school night, kid. Shouldn't you be home?"],
		["FRANKIE", "My mom works nights at the hospital. Home's a TV and a microwave. This place has a lift."],
		["choice", [["\"Grab that light. Hold it where I'm looking.\"", "kid_light"], ["\"Does anybody know where you are?\"", "kid_home"], ["\"Shop's closed, kid.\"", "kid_closed"]]],
		["FRANKIE", "My mom knows I'm out. Kind of. I'll text her right now. Can I hold the light while I text her?", { "flag": "kid_home" }],
		["FRANKIE", "It's not closed. Gus is still here.", { "flag": "kid_closed" }],
		["GUS", "Don't look at me, kid. You're the boss. Apparently.", { "flag": "kid_closed" }],
		["FRANKIE", "I'll hold the light. I'm really good at holding stuff. Ten minutes and then I'll go. Probably."],
		["*", "HE HOLDS THE LIGHT FOR TWO HOURS. HE DOESN'T MOVE IT ONCE. NOT EVEN WHEN LEO DROPS THE 10 MIL DOWN THE BRAKE DUCT AND SAYS A WORD YOU DON'T SAY IN FRONT OF A KID."],
		["pose", "LEO", "pockets"],
		["LEO", "Okay. Saturday. Daytime. You text your mom first, and you touch nothing I don't hand you. What's your name?"],
		["FRANKIE", "Frankie."],
		["pose", "GUS", "stand"],
		["GUS", "...Frankie."],
		["GUS", "Only one man ever called your father that. Dale Hatch."],
		["GUS", "Your father hated it."],
		["FRANKIE", "Is that bad? I can be Frank. Nobody calls me Frank."],
		["LEO", "Frankie's fine. It's just a name."],
		["*", "IT'S JUST A NAME. GUS GOES INTO THE BACK OFFICE AND SHUTS THE DOOR. THROUGH THE GLASS, LEO WATCHES HIM TAKE A PHOTO DOWN OFF THE WALL AND LOOK AT IT FOR A LONG TIME."],
		["flag", "frankie_met"],
		["flag", "clue_frankie"],
	]},
	"frankie": { "set": "bay", "cast": [["MIKEY", 28, 1, "pockets"], ["ARIES", 72, 1, "crossed"], ["LEO", 124, 1, "stand"], ["FRANKIE", 172, -1, "stand"]], "lines": [
		["*", "COVINGTON AUTO. A SATURDAY IN JUNE. FRANKIE HASN'T MISSED A SATURDAY SINCE NOVEMBER. OR MOST WEDNESDAYS. OR ONE CHRISTMAS EVE NOBODY TALKS ABOUT."],
		["FRANKIE", "Pads are at three mil. The rotor's got a lip on it. The slides are dry. That's a fail."],
		["LEO", "That's a fail. Write it up."],
		["MIKEY", "He's better at this than you were. He's better at this than you ARE."],
		["ARIES", "He fixed my bike. It shifts now. It never shifted."],
		["FRANKIE", "It shifted. Into the wrong gears."],
		["FRANKIE", "Mikey says you did a hundred and forty through a fence once. And you lost the cops on Main last week. Is that true?", { "karma": "low" }],
		["LEO", "...Some of it.", { "karma": "low" }],
		["FRANKIE", "Sick.", { "karma": "low" }],
		["LEO", "Every Sunday you check your brakes. Every Sunday. Even when you think they're fine. Especially then.", { "karma": "not_low" }],
		["FRANKIE", "You always say that.", { "karma": "not_low" }],
		["LEO", "My dad always said that.", { "karma": "not_low" }],
		["FRANKIE", "Do you check yours? Every Sunday?", { "karma": "low" }],
		["LEO", "...I used to.", { "karma": "low" }],
		["flag", "sunday_lesson", { "karma": "high" }],
		["choice", [["\"He'd have liked you.\"", "mentor_dad"], ["\"Next week you do the whole job. I don't touch it.\"", "mentor_job"], ["\"Go wash up. Pizza's on Mikey.\"", "mentor_pizza"]]],
		["MIKEY", "Pizza's always on Mikey. Nobody ever asks Mikey."],
		["FRANKIE", "Can I get a Covington Auto shirt? A real one. With the name thing on it."],
		["set", "office"],
		["cast", [["GUS", 96, 1, "stand"], ["FRANKIE", 150, -1, "stand"]]],
		["*", "GUS DIGS ONE OUT OF A BOX IN THE BACK. A SMALL. HE SEWS FRANKIE'S NAME ON IT HIMSELF, AT THE COUNTER, WITH HIS READING GLASSES ON, AND TELLS NOBODY HE DID IT."],
		["*", "FRANKIE WEARS IT HOME OVER HIS HOODIE. HE WEARS IT EVERY SATURDAY AFTER THAT. HE'S IN THE PHOTOS ON THE BREAK ROOM WALL NOW."],
		["flag", "frankie_crew"],
	]},
	# ------------------------------------------------------------------ the finale: the Mountain
	"hatch_counter": { "set": "office", "cast": [["LEO", 110, 1, "stand"], ["HATCH", 196, -1, "hips"]], "lines": [
		["*", "DECEMBER 2026. COVINGTON AUTO, THE FRONT COUNTER. SIX WINTERS AFTER THE FENCE."],
		["*", "DALE HATCH BRINGS HIS OWN CHARJER IN FOR ITS STICKER. HE ALWAYS HAS. IT'S A SHOW OF TRUST."],
		["HATCH", "Morning, kid. Papers are perfect. They're always perfect."],
		["HATCH", "Heard about you on the Main Street Mile. Heard about the fence, too, way back. Your father was the same. Fast. Right up until he wasn't.", { "karma": "low" }],
		["HATCH", "Heard the Ministry quit auditing this counter. Only one in Port Rumble. Your father would've liked that.", { "karma": "high" }],
		["HATCH", "And your young fella's driving now. Frankie. Good kid. Wears the shirt. Had the Silvio in for winter tires this morning. On the house."],
		["LEO", "Dad never let anybody call him Frankie."],
		["HATCH", "Me he did. Frankie and his little green book. Every Sunday, every brake line, in pencil."],
		["pose", "LEO", "crossed"],
		["*", "NOBODY KNEW ABOUT THAT BOOK BUT GUS AND FRANK'S KIDS. GUS SAID SO, IN BAY 3, SIX YEARS AGO. LEO WROTE IT DOWN."],
		["*", "DALE HATCH SEES LEO'S FACE. HE STOPS SMILING."],
		["choice", [["Stamp the sticker. Smile back. Call Tremblay once he's gone.", "hatch_calm"], ["\"How do you know about the book, Dale?\"", "hatch_threat"]]],
		["HATCH", "...Small town, kid. Small town.", { "flag": "hatch_calm" }],
		["HATCH", "I knew your father a lot longer than you did, kid. Careful what you say at this counter. It's a nice counter.", { "flag": "hatch_threat" }],
		["*", "HE TAKES HIS KEYS AND LEAVES. HE DOESN'T WAIT FOR THE STICKER."],
		["flag", "hatch_slip"],
	]},
	"first_snow": { "set": "apartment", "cast": [["LEO", 150, 1, "phone"]], "lines": [
		["*", "THAT NIGHT. THE FIRST SNOW. FRANKIE'S BEEN DRIVING THE OLD SILVIO SINCE LEO GAVE IT TO HIM FOR HIS EIGHTEENTH."],
		["*", "LEO'S PHONE GOES AT 11:52."],
		# HIGH: he did his Sunday check, because Leo taught him to
		["FRANKIE19", "did my sunday check early bc of the snow", { "karma": "high" }],
		["FRANKIE19", "leo my rear brake line is cut. clean. like with a tubing cutter", { "karma": "high" }],
		["FRANKIE19", "it was only at hatch motors today. for tires. he said on the house", { "karma": "high" }],
		["FRANKIE19", "im not driving it. im at the tim burtons on mountain rd", { "karma": "high" }],
		["LEO", "Don't touch it. Don't move. I'm coming, and I'm calling Tremblay.", { "karma": "high" }],
		["flag", "frankie_safe", { "karma": "high" }],
		# MIDDLE: he skipped it, once, and lived
		["FRANKIE19", "leo", { "karma": "middle" }],
		["FRANKIE19", "brakes went coming down the mountain. no pedal. put it in the snowbank at the hairpin like u showed me", { "karma": "middle" }],
		["FRANKIE19", "my arm is bent wrong", { "karma": "middle" }],
		["FRANKIE19", "i skipped the sunday check. first time ever. it was at hatch motors for tires today", { "karma": "middle" }],
		["LEO", "Don't move. I'm coming.", { "karma": "middle" }],
		["flag", "frankie_hurt", { "karma": "middle" }],
		# LOW: he learned the wrong things from Leo
		["*", "IT ISN'T FRANKIE. IT'S TOBY.", { "karma": "low" }],
		["TOBY", "Leo. Pick up. Pick up.", { "karma": "low" }],
		["TOBY", "It's the Silvio. The hairpin at the top of Mountain Rd. Frankie had it at Hatch Motors today for tires.", { "karma": "low" }],
		["TOBY", "There's no skid marks, Leo. In fresh snow. Same as your dad.", { "karma": "low" }],
		["TOBY", "He's gone. I'm sorry. He's gone.", { "karma": "low" }],
		["*", "LEO NEVER REALLY TOLD HIM ABOUT SUNDAYS. HE TOLD HIM ABOUT A HUNDRED AND FORTY THROUGH A FENCE.", { "karma": "low" }],
		["flag", "frankie_dead", { "karma": "low" }],
	]},
	"clean_end": { "set": "tims", "cast": [["TREMBLAY", 127, 1, "crossed"], ["HATCH", 146, 1, "stand"], ["LEO", 165, -1, "stand"], ["FRANKIE19", 184, -1, "pockets"]], "lines": [
		["*", "MOUNTAIN RD, IN FRONT OF THE TIM BURTONS. 1:10 A.M. TREMBLAY'S CRUISER ACROSS BOTH LANES."],
		["*", "DALE HATCH'S CHARJER COMES DOWN THE MOUNTAIN AT EXACTLY THE SPEED LIMIT. IT STOPS AT THE CRUISER. IT HAS NOWHERE ELSE TO GO."],
		["TREMBLAY", "Mr. Hatch. Step out of the car, please."],
		["HATCH", "Constable. It's late. Whatever this is, my lawyer can—"],
		["TREMBLAY", "December 2018. Frank Covington. No skid marks in fresh snow. I wrote that down. Nobody wanted it."],
		["TREMBLAY", "Tonight: a brake line cut clean, on a car that was in your shop this morning. The kid checked his brakes. He checks them every Sunday."],
		["HATCH", "...Frankie and his Sundays."],
		["TREMBLAY", "Hands on the roof, Mr. Hatch."],
		["FRANKIE19", "You okay?"],
		["LEO", "Yeah. I'm okay."],
		["set", "bay"],
		["cast", [["GUS", 96, 1, "stand"], ["FRANKIE19", 132, -1, "stand"], ["LEO", 168, -1, "pockets"]]],
		["*", "GUS IS WAITING AT THE SHOP WHEN THEY GET BACK. HE DOESN'T SAY ANYTHING. HE PUTS A HAND ON FRANKIE'S SHOULDER AND KEEPS IT THERE."],
		["*", "ON SUNDAY, LEO CHECKS HIS BRAKES. SO DOES FRANKIE. SO DOES GUS, FOR THE FIRST TIME IN THIRTY YEARS."],
	]},
	"middle_end": { "set": "office", "cast": [["LEO", 100, 1, "stand"], ["FRANKIE19", 156, -1, "stand"], ["GUS", 232, -1, "crossed"]], "lines": [
		["*", "TWO WEEKS LATER. FRANKIE'S ARM IS IN A CAST. HE'S WORKING THE COUNTER ONE-HANDED, BECAUSE HE REFUSES NOT TO."],
		["*", "TREMBLAY COULDN'T MAKE IT STICK. THE SILVIO SAT IN A SNOWBANK FOR SIX HOURS BEFORE ANYBODY LOOKED AT THE LINE, AND A LAWYER FROM HALIFAX SAID \"WEAR AND TEAR\" FORTY TIMES."],
		["GUS", "Hatch sold the lot. Signed this building over to the shop on his way out, if you can believe it. The paperwork's perfect. It's always perfect."],
		["GUS", "He's in Alberta. Or he's on a boat. Depends who you ask."],
		["LEO", "He's just gone? After all of it?"],
		["GUS", "Men like Dale don't get caught, kid. They get bored, or they get old. We'll see which."],
		["FRANKIE19", "I'm doing the Sunday check from now on. Every Sunday. Even when I think they're fine."],
		["LEO", "Especially then."],
	]},
	"funeral": { "set": "lot_dusk", "cast": [["MIKEY", 124, 1, "pockets"], ["ARIES", 158, 1, "crossed"], ["GUS", 194, 1, "stand"], ["LEO", 244, -1, "stand"], ["TOBY", 284, -1, "pockets"]], "lines": [
		["*", "COVINGTON AUTO. FOUR DAYS LATER. NOBODY OPENED THE BAYS."],
		["*", "THEY BURIED HIM IN THE SHIRT. THE SMALL ONE. HIS MOM SAID IT STILL FIT IF YOU DIDN'T DO THE BUTTONS."],
		["GUS", "He held that light for two hours. Didn't move it once."],
		["MIKEY", "He thought you were the coolest guy in Port Rumble, bud. He wanted to be you."],
		["ARIES", "That's the problem, Mikey."],
		["TOBY", "No skid marks. I've towed two cars off that mountain with no skid marks, Leo. Your dad's and his."],
		["LEO", "It's Hatch. It was always Hatch. The green book. The tires. On the house."],
		["GUS", "Leo. Let Tremblay—"],
		["LEO", "Tremblay wrote it down six years ago. Nobody wanted it."],
		["*", "DALE HATCH DRIVES UP MOUNTAIN RD EVERY NIGHT AROUND ELEVEN, TO HIS PLACE PAST THE HILL. EVERYBODY KNOWS THAT."],
		["ARIES", "Leo. Don't."],
		["set", "lot_dusk_charjer"],
		["cast", [["LEO", 200, -1, "stand"]]],
		["*", "HE GOES."],
		["flag", "revenge"],
	]},
	"street_end": { "set": "tims", "cast": [["TOBY", 128, 1, "crossed"], ["LEO", 156, -1, "stand"], ["TREMBLAY", 184, -1, "crossed"]], "lines": [
		["*", "THE HAIRPIN AT THE TOP OF MOUNTAIN RD. THERE'S A GAP IN THE GUARDRAIL THE SHAPE OF A CHARJER."],
		["*", "DALE HATCH LIVED. HE'LL NEVER WALK RIGHT. HE TALKED FOR SIX HOURS IN THE HOSPITAL: 1987, THE PIPELINE, THE BRAKES, THE BLOOD SAMPLE, THE TIRES. TREMBLAY WROTE ALL OF IT DOWN."],
		["TOBY", "I'll tow it. I tow everything off this mountain."],
		["TOBY", "But I want you to know what you look like right now, Leo. You look like him. Not your dad. Him."],
		["TREMBLAY", "Leo Covington. Turn around, please."],
		["LEO", "...Yeah."],
		["*", "LEO SITS IN THE BACK OF THE CRUISER. HE CAN SEE THE SHOP SIGN FROM HERE. SOMEBODY LEFT THE BAY LIGHT ON."],
		["set", "office"],
		["cast", [["GUS", 96, 1, "crossed"], ["MIKEY", 140, -1, "pockets"], ["ARIES", 182, -1, "phone"]]],
		["*", "THREE YEARS LESS A DAY. GUS KEEPS THE COUNTER. MIKEY KEEPS THE HAT. EVERY SUNDAY, ARIES CHECKS THE BRAKES ON THE SUPREEM AND SENDS HIM A PHOTO OF THE PADS."],
	]},
}

## The order of the story. "mission" ids are in StoryMissions.
const STEPS := [
	{ "type": "card", "title": "PROLOGUE", "sub": "LAST CALL", "small": "PORT RUMBLE, NEW BRUNSWICK. OCTOBER 2019." },
	{ "type": "scene", "id": "party" },
	{ "type": "drive", "mission": "last_call" },
	{ "type": "scene", "id": "the_meet" },
	{ "type": "card", "title": "THE NEXT MORNING", "sub": "", "small": "COVINGTON AUTO" },
	{ "type": "scene", "id": "gus_morning" },
	{ "type": "avatar" },
	{ "type": "counter", "day": 0, "tutorial": true },
	{ "type": "scene", "id": "clock_out_1" },
	{ "type": "drive", "mission": "runs_great" },
	{ "type": "scene", "id": "runs_great" },
	{ "type": "drive", "mission": "drive_it_home" },
	{ "type": "scene", "id": "home_night" },
	{ "type": "card", "title": "CHAPTER 1", "sub": "WRONG TURF", "small": "YEAR ONE. LEO IS 19.", "day_ends": true, "karma": true },
	{ "type": "counter", "day": 1 },
	{ "type": "scene", "id": "clock_out_2" },
	{ "type": "drive", "mission": "detailing" },
	{ "type": "scene", "id": "bay_three" },
	{ "type": "scene", "id": "the_kid" },
	# (the rest of the winter goes here: Dom's drag lessons, Johnny Tram, the first snow)
	{ "type": "card", "title": "JUNE 2020", "sub": "SATURDAYS", "small": "EIGHT MONTHS OF COUNTER SHIFTS LATER. THE KID KEEPS COMING BACK." },
	{ "type": "scene", "id": "frankie" },
	# (chapters 2 to 7 go here: the years in between)
	{ "type": "card", "title": "CHAPTER 8", "sub": "THE MOUNTAIN", "small": "DECEMBER 2026. LEO IS 26. FRANKIE IS 19. (CHAPTERS 2 TO 7, THE YEARS IN BETWEEN, ARE STILL BEING WRITTEN.)", "karma": true },
	{ "type": "scene", "id": "hatch_counter" },
	{ "type": "scene", "id": "first_snow" },
	# the ending was settled the night of the first snow: by what Leo taught Frankie
	{ "type": "drive", "mission": "long_way_down", "if": { "flag": "frankie_safe" } },
	{ "type": "scene", "id": "clean_end", "if": { "flag": "frankie_safe" } },
	{ "type": "drive", "mission": "snowbank", "if": { "flag": "frankie_hurt" } },
	{ "type": "scene", "id": "middle_end", "if": { "flag": "frankie_hurt" } },
	{ "type": "scene", "id": "funeral", "if": { "flag": "frankie_dead" } },
	{ "type": "drive", "mission": "the_mountain", "if": { "flag": "frankie_dead" } },
	{ "type": "scene", "id": "street_end", "if": { "flag": "frankie_dead" } },
	{ "type": "card", "title": "THE END", "sub": "CLEAN", "small": "DALE HATCH WAS CONVICTED ON EVERY COUNT. FRANKIE RUNS THE COUNTER ON SATURDAYS.", "if": { "flag": "frankie_safe" } },
	{ "type": "card", "title": "THE END", "sub": "GONE", "small": "NOBODY'S SEEN DALE HATCH SINCE. FRANKIE'S CAST CAME OFF IN FEBRUARY. HE SIGNED IT FIRST.", "if": { "flag": "frankie_hurt" } },
	{ "type": "card", "title": "THE END", "sub": "THE MOUNTAIN", "small": "FRANKIE, 2007 - 2026. HE HELD THE LIGHT.", "if": { "flag": "frankie_dead" } },
	{ "type": "credits" },
]
