## The story, as data: who's in it, what they say, and the order things happen in.
##
## A scene is a set (a background drawn by code) and a list of lines:
##   [speaker, text]               a line of dialogue ("*" is narration, no portrait)
##   ["choice", [[label, flag], ...]]   Leo picks; the flag is remembered
##   ["set", name]                 change the background mid-scene
##   ["cash", amount]              money changes hands
##   ["flag", name]                remember something
##   ["pose", who, pose]           someone in the scene changes pose (stand, crossed, pockets, cup, phone, bow, point, hips, wave)
## A scene's "cast" is who's standing in the set: [who, x (0..320), facing (1 right / -1 left), pose].
## Anyone who speaks but isn't in the cast is on Leo's phone (texts).
## Text can use {MANAGER} (the old manager's name), {CASH} and {DEBT}.
class_name StoryScript
extends RefCounted

## The cast. seed + female + age go straight into the CAGE BOSS portrait generator.
const CAST := {
	"LEO":       { "name": "LEO", "seed": 190019, "female": 0, "age": 19, "color": "d9a441" },
	"MIKEY":     { "name": "MIKEY", "seed": 420069, "female": 0, "age": 19, "color": "6fbf5a" },
	"GUS":       { "name": "GUS", "seed": 198101, "female": 0, "age": 70, "color": "c8c0a8" },
	"DOM":       { "name": "DOM TORTELLINI", "seed": 777001, "female": 0, "age": 46, "color": "e0402e" },
	"MIA":       { "name": "MIA TORTELLINI", "seed": 777002, "female": 1, "age": 38, "color": "e07a9a" },
	"SAL":       { "name": "SAL", "seed": 777013, "female": 0, "age": 33, "color": "a85a4a" },
	"ARIES":     { "name": "ARIES", "seed": 140014, "female": 1, "age": 14, "color": "7ab8e0" },
	"TOBY":      { "name": "TOBY CORMIER", "seed": 506506, "female": 0, "age": 31, "color": "ffa020" },
	"TREMBLAY":  { "name": "CONST. TREMBLAY", "seed": 911911, "female": 1, "age": 41, "color": "4a7ab8" },
	"DARRELL":   { "name": "DARRELL (SELLER)", "seed": 900900, "female": 0, "age": 58, "color": "8a8478" },
	"FRANK":     { "name": "FRANK COVINGTON", "seed": 190001, "female": 0, "age": 49, "color": "c8c0a8" },
}

const SCENES := {
	# ------------------------------------------------------------------ prologue
	"party": { "set": "party", "cast": [["LEO", 120, 1, "cup"], ["MIKEY", 186, -1, "cup"]], "lines": [
		["*", "A WAREHOUSE ON INDUSTRIAL DRIVE. SOMEBODY'S COUSIN'S BIRTHDAY. NOBODY KNOWS WHOSE."],
		["MIKEY", "Leo. LEO. Buddy. You've been staring at that speaker for ten minutes."],
		["LEO", "It's breathing, Mikey. The speaker's breathing."],
		["MIKEY", "That's the bass, man. Also the edible. Mostly the edible."],
		["LEO", "Ten months tomorrow. Since Dad."],
		["MIKEY", "...Yeah. I know, bud."],
		["LEO", "Everybody keeps saying he was drunk. Twenty years sober and he goes off the Coast Road with a forty in him? Sure."],
		["MIKEY", "You want to talk about it?"],
		["LEO", "I want another one of whatever this is."],
		["*", "TWO HOURS AND SEVERAL BAD DECISIONS LATER."],
		["MIKEY", "Where are you going? Your keys are in my hat. Why are your keys in my hat."],
		["LEO", "Taking Dad's Supreem home. It's two kilometres. It's fine."],
		["MIKEY", "Are you good to drive?"],
		["choice", [["\"I'm always good to drive.\"", "cocky"], ["\"...Yeah.\"", "quiet"], ["\"Mikey. Look at me. I'm a professional.\"", "joke"]]],
		["MIKEY", "...Text me when you're home. Use words. Not just the eggplant."],
	]},
	"the_meet": { "set": "airstrip", "cast": [["MIA", 34, 1, "hips"], ["LEO", 216, -1, "stand"], ["DOM", 252, -1, "crossed"], ["SAL", 292, -1, "pockets"]], "lines": [
		["*", "AIRSTRIP 7. FRIDAY NIGHT. THE FAMILIA'S MEET."],
		["*", "TWENTY CARS IN A CIRCLE. HEADLIGHTS ON. ONE OF THEM IS NOW INSIDE ANOTHER ONE."],
		["MIA", "That's my car. That WAS my car. Dom. DOM. He parked in my car."],
		["SAL", "Kid came through the fence at like a hundred and forty. Nobody was chasing him. He was chasing himself."],
		["LEO", "I'm... okay. I'm okay. Is everybody okay? Whose turbo is that on the ground?"],
		["MIA", "MINE. That's my turbo. On the ground. Where turbos don't go."],
		["DOM", "Everybody. Quiet."],
		["*", "DOM TORTELLINI WALKS AROUND THE WRECK ONCE. SLOWLY. THEN HE BOWS HIS HEAD."],
		["pose", "DOM", "bow"],
		["pose", "SAL", "bow"],
		["DOM", "Lord. Thank you for this meet. For the cars. For the family. For the kid who didn't die tonight, even though he tried his best."],
		["DOM", "Amen."],
		["SAL", "Amen."],
		["pose", "DOM", "crossed"],
		["pose", "SAL", "pockets"],
		["MIA", "...Amen. I'm still going to kill him."],
		["DOM", "You're Frank Covington's boy."],
		["LEO", "You knew my dad?"],
		["DOM", "Everybody knew your dad. Your dad fixed my first car on credit. Never asked for the money. Never had to."],
		["pose", "DOM", "point"],
		["DOM", "You broke family's car. So now you work for family."],
		["pose", "DOM", "crossed"],
		["DOM", "Your father's garage? It's a nice garage. Be a shame if it was... legitimate."],
		["LEO", "It has an inspection licence. You can't just—"],
		["DOM", "I know. That's why it's a nice garage."],
		["MIA", "Forty-two hundred. For the car. Plus my turbo. Plus my feelings."],
		["DOM", "Mia. We're not monsters. Forty-two hundred. The feelings are free."],
		["choice", [["\"Okay. Okay. I'll pay it.\"", "meet_agree"], ["\"And if I say no?\"", "meet_defiant"]]],
		["DOM", "Then you say no, and tomorrow you still owe us, and you're also the kid who said no. Go home, Leo. Walk. Sal will bring the car."],
		["SAL", "The car's in four pieces, Dom."],
		["DOM", "Then bring all four. Family doesn't leave pieces behind."],
		["flag", "owes_familia"],
	]},
	"gus_morning": { "set": "office", "cast": [["GUS", 70, 1, "crossed"], ["LEO", 246, -1, "stand"]], "lines": [
		["*", "COVINGTON AUTO. 7:58 A.M. LEO HAS A HEADACHE SHAPED LIKE A SUPREEM."],
		["GUS", "You look like something I'd drain out of a transmission."],
		["LEO", "Morning, Gus."],
		["GUS", "Toby towed what's left of your father's car in at six. Says you went through a fence at Airstrip 7."],
		["GUS", "Says the Tortellinis were there. Says Dom said grace."],
		["LEO", "He's... a very spiritual man."],
		["GUS", "He's a very something man."],
		["GUS", "Front counter's yours now. Your father left you the shop, and the shop comes with the counter, and the counter comes with the Ministry."],
		["GUS", "Every car that wants a sticker, you read every paper. VIN on the ownership against the VIN on the dash. I read it off the car myself. Every one."],
		["LEO", "Who ran the counter before Dad's... before?"],
		["GUS", "{MANAGER}. Ran it for years, then one day didn't. Left a drawer full of pens and a coffee mug that says WORLD'S OKAYEST BOSS."],
		["pose", "GUS", "point"],
		["GUS", "Don't touch the mug."],
	]},
	"clock_out_1": { "set": "lot_dusk", "cast": [["GUS", 92, 1, "crossed"], ["LEO", 150, -1, "pockets"]], "lines": [
		["*", "CLOCK OUT. 6:02 P.M."],
		["GUS", "Not bad. Not good. Not bad. Your father's first day he passed a car with no brakes, so you're ahead of him."],
		["LEO", "Dad passed a car with no brakes?"],
		["GUS", "Once. Never again. Checked his own every Sunday after that. Every single Sunday."],
		["pose", "LEO", "phone"],
		["*", "LEO'S PHONE BUZZES. TWICE."],
		["ARIES", "are u alive. toby said u drove into the mafia"],
		["LEO", "Not the mafia. A family. With a lot of cars."],
		["ARIES", "thats the mafia leo"],
		["ARIES", "also we have no milk. and no car. and i have practice at 7 tomorrow"],
		["*", "ANOTHER BUZZ. MIKEY."],
		["MIKEY", "found u a car on MarketThing. $900. 'RUNS GREAT.' guy says meet at the Tims on Mountain Rd. bring cash. i put in $500 from my college fund (the jar)"],
		["LEO", "Mikey, that jar is for college."],
		["MIKEY", "bro the jar is for emergencies. u are an emergency"],
		["TOBY", "Heard you need a ride to the Tim's. Take the wrecker. Don't touch the boom. Don't touch the radio. Don't eat the timbits on the dash, they're evidence."],
	]},
	"runs_great": { "set": "tims", "cast": [["LEO", 124, 1, "stand"], ["DARRELL", 172, -1, "hips"]], "lines": [
		["*", "TIM BURTONS, MOUNTAIN ROAD. A '91 NISSUN SILVIO UNDER THE ONLY LAMP THAT WORKS."],
		["DARRELL", "You Mikey's guy?"],
		["pose", "LEO", "pockets"],
		["LEO", "I'm Mikey's guy."],
		["DARRELL", "Runs great. Needs nothing. Selling it for my wife's husband."],
		["LEO", "...Isn't that you?"],
		["DARRELL", "Hence the price."],
		["pose", "LEO", "point"],
		["LEO", "Why's there a puddle under it?"],
		["pose", "LEO", "stand"],
		["DARRELL", "That's a rain puddle."],
		["LEO", "It hasn't rained in a week."],
		["DARRELL", "It's a very old rain puddle. Nine hundred. No lowballs, I know what I have."],
		["choice", [["Pop the hood first.", "checked_silvio"], ["\"Deal.\" (Hand over the cash.)", "blind_buy"]]],
		["DARRELL", "Oil's a little milky. That's normal. That's how they came from the factory. Like a latte."],
		["DARRELL", "That's eight-forty. I said nine."],
		["LEO", "It's everything I have. And everything Mikey's jar had."],
		["DARRELL", "...Fine. The other sixty was for the puddle anyway."],
		["cash", -340],
		["DARRELL", "Pleasure doing business. Don't call me. The number's my wife's husband's."],
		["flag", "owns_silvio"],
		["*", "IT STARTS ON THE THIRD TRY. IT SOUNDS LIKE A BLENDER FULL OF BOLTS. IT IS THE MOST BEAUTIFUL THING LEO HAS EVER OWNED."],
	]},
	"home_night": { "set": "apartment", "cast": [["LEO", 140, 1, "stand"], ["ARIES", 222, -1, "crossed"]], "lines": [
		["*", "THE APARTMENT OVER THE GARAGE. 11:40 P.M."],
		["ARIES", "Is that your new car? It sounds like it's crying."],
		["LEO", "It's singing."],
		["ARIES", "It's leaking on Gus's spot. He's going to kill you."],
		["ARIES", "...Leo. You smelled like a bar last night. Toby told me about the fence."],
		["LEO", "I'm fine."],
		["ARIES", "Dad used to say that. Right up until."],
		["*", "SHE GOES TO BED. LEO SITS IN THE DARK FOR A WHILE. THE SILVIO TICKS AS IT COOLS DOWN IN THE BAY BELOW."],
	]},
	# ------------------------------------------------------------------ chapter 1
	"clock_out_2": { "set": "lot_dusk_charjer", "cast": [["LEO", 118, 1, "stand"], ["MIA", 176, -1, "hips"]], "lines": [
		["*", "CLOCK OUT. A BLACK DODGY CHARJER IS IDLING ACROSS THE STREET. IT HAS BEEN IDLING ACROSS THE STREET FOR AN HOUR."],
		["MIA", "Leo. Walk with me."],
		["pose", "MIA", "crossed"],
		["MIA", "Dom wants you to start paying. Tonight there's a car at Airstrip 7. Black Charjer, the other one. Bring it here. Bay 3."],
		["LEO", "What's wrong with it?"],
		["MIA", "Nothing's wrong with it. Something's wrong with its paperwork. That's your department now."],
		["MIA", "Not a scratch on it, Leo. Every scratch comes off your forty-two hundred. In the wrong direction."],
		["LEO", "Mia, I'm sorry about your car."],
		["MIA", "...It was a good car. My dad built it. Don't make me cry in front of the Tim's."],
	]},
	"bay_three": { "set": "bay", "cast": [["LEO", 100, 1, "pockets"], ["GUS", 160, -1, "stand"]], "lines": [
		["*", "BAY 3. THE CHARJER SITS UNDER A TARP. GUS IS NOT LOOKING AT IT VERY HARD."],
		["GUS", "Your father had a bay like this once. Before you were born. Before he went straight."],
		["LEO", "Dad never talked about before."],
		["GUS", "No. He didn't."],
		["GUS", "He checked his brakes every Sunday, Leo. Every Sunday for twenty years. You know what kind of man misses his brakes the one week it snows?"],
		["LEO", "A drunk one. That's what the report says."],
		["pose", "GUS", "crossed"],
		["GUS", "Report says a lot of things. Reports get written by people."],
		["*", "GUS GOES BACK TO WORK. HE DOESN'T SAY ANOTHER WORD ALL NIGHT."],
		["flag", "clue_brakes"],
	]},
}

## The order of the story. "mission" ids are in StoryMissions.
const STEPS := [
	{ "type": "card", "title": "PROLOGUE", "sub": "LAST CALL", "small": "PORT RUMBLE, NEW BRUNSWICK. OCTOBER 2019." },
	{ "type": "scene", "id": "party" },
	{ "type": "drive", "mission": "last_call" },
	{ "type": "scene", "id": "the_meet" },
	{ "type": "card", "title": "THE NEXT MORNING", "sub": "", "small": "COVINGTON AUTO" },
	{ "type": "scene", "id": "gus_morning" },
	{ "type": "avatar" },
	{ "type": "counter", "day": 0, "tutorial": true },
	{ "type": "scene", "id": "clock_out_1" },
	{ "type": "drive", "mission": "runs_great" },
	{ "type": "scene", "id": "runs_great" },
	{ "type": "drive", "mission": "drive_it_home" },
	{ "type": "scene", "id": "home_night" },
	{ "type": "card", "title": "CHAPTER 1", "sub": "WRONG TURF", "small": "YEAR ONE. LEO IS 19.", "day_ends": true },
	{ "type": "counter", "day": 1 },
	{ "type": "scene", "id": "clock_out_2" },
	{ "type": "drive", "mission": "detailing" },
	{ "type": "scene", "id": "bay_three" },
	{ "type": "card", "title": "TO BE CONTINUED", "sub": "CHAPTER 1 CONTINUES IN THE NEXT BUILD", "small": "DOM'S DRAG LESSONS, JOHNNY TRAM, AND THE FIRST SNOW." },
]
